# Generated by Django 4.2.5 on 2023-11-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_like"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
