# Generated by Django 4.2.5 on 2023-11-04 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_category"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="Category",
        ),
    ]
