# Generated by Django 4.2.5 on 2023-10-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilemodel",
            name="category",
            field=models.CharField(default="Content Creator", max_length=255),
        ),
    ]
