# Generated by Django 4.2.5 on 2023-10-10 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profilemodel_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="image",
            field=models.ImageField(
                default="default.png",
                upload_to="profile",
                validators=[
                    django.core.validators.FileExtensionValidator(["png", "jpg"])
                ],
            ),
        ),
    ]
