# Generated by Django 4.2.5 on 2023-11-04 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_category_profiledetails"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="Category",
        ),
    ]
