# Generated by Django 4.2.5 on 2023-11-04 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_category_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table=None,
        ),
    ]
