# Generated by Django 4.2.5 on 2023-11-04 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_category_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
